services:
  loki:
    image: grafana/loki:${LOKI_VERSION:-3.5.5}
    container_name: loki
    command: [
      "-config.file=/etc/loki/loki.yaml"
    ]
    user: root
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./loki_data:/loki
      - ./loki_conf/loki.yaml:/etc/loki/loki.yaml
    ports:
      - 3100:3100
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://127.0.0.1:3100/metrics"]
      interval: 10s
      timeout: 10s
      retries: 3