services:
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: always
    # network_mode: host
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_URI=postgresql:5432/${POSTGRES_DB:-api7ee}?sslmode=disable
      - DATA_SOURCE_USER=${POSTGRES_USER:-api7ee}
      - DATA_SOURCE_PASS=${POSTGRES_PASSWORD:-api7ee}
    command:
      - --config.file=/conf/postgres-exporter.yaml
    volumes:
      - ./postgres_exporter_conf/postgres-exporter.yaml:/conf/postgres-exporter.yaml
    ports:
      - 9187:9187
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://127.0.0.1:9187/metrics"]
      interval: 10s
      timeout: 10s
      retries: 3