services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-main}
    restart: always
    hostname: prometheus
    container_name: prometheus
    environment:
      - TZ=Asia/Bangkok
    command: [
      "--config.file=/conf/prometheus.yaml",
      "--storage.tsdb.retention.time=90d",
      "--enable-feature=exemplar-storage,native-histograms",
      "--web.listen-address=0.0.0.0:9090",
      "--web.enable-lifecycle",
      "--web.enable-remote-write-receiver"
    ]
    
    volumes:
      - ./prometheus_conf/prometheus.yaml:/conf/prometheus.yaml
      - ./prometheus_data:/prometheus
    ports:
      - 9090:9090
    healthcheck:
      test: ["CMD", "/bin/promtool", "check", "healthy"]
      interval: 10s
      timeout: 10s
      retries: 3

# Before start
# mkdir -p prometheus_data
# chown -R 65534:65534 prometheus_data

# reload prometheus config
# docker exec prometheus kill -HUP 1